#!/bin/bash

# Nefarious IRCd Docker Entrypoint
# Reads base.conf-dist, replaces all %VARIABLE% placeholders with environment
# variable values, and writes out base.conf
# Volume permissions are handled by init container in docker-compose

BASECONFDIST=/home/nefarious/ircd/base.conf-dist
BASECONF=/home/nefarious/ircd/base.conf
IRCDPEM=/home/nefarious/ircd/ircd.pem

# Set defaults for required variables (can be overridden by environment)
: "${IRCD_GENERAL_NAME:=localhost.localdomain}"
: "${IRCD_GENERAL_DESCRIPTION:=localhost.localdomain}"
: "${IRCD_ADMIN_LOCATION:=Somewhere}"
: "${IRCD_ADMIN_CONTACT:=root@localhost}"
: "${IRCD_GENERAL_NUMERIC:=1}"

# Marker stamped as the first line of every base.conf THIS script generates.
# Regeneration policy:
#   - no base.conf                 -> generate (and stamp the marker)
#   - base.conf WITH the marker    -> regenerate: env + template are the
#                                     source of truth
#   - base.conf WITHOUT the marker -> user-managed (e.g. volume-mounted,
#                                     hand-edited) -> never touched.
#                                     Previously an unconditional cp
#                                     clobbered such files on every start.
GENMARKER='# GENERATED BY dockerentrypoint.sh from base.conf-dist. Do not hand-edit: this file is REGENERATED ON EVERY CONTAINER START while this marker is the first line. To manage base.conf yourself, replace it with a file that lacks this marker.'

if [ -f "$BASECONF" ] && ! head -n 1 "$BASECONF" | grep -qF 'GENERATED BY dockerentrypoint.sh'; then
    echo "Found user-managed config at $BASECONF (no generation marker), leaving it alone"
else
    # Substitute into a temp copy, then stamp the marker and move into
    # place, so a crash mid-generation never leaves a half-substituted
    # marker-less (= treated as user-managed) conf behind.
    GENTMP="$BASECONF.gen.$$"
    cp "$BASECONFDIST" "$GENTMP"

    # Find all %VARIABLE% placeholders in the config and substitute them
    # with corresponding environment variable values
    grep -oE '%[A-Za-z_][A-Za-z0-9_]*%' "$GENTMP" | sort -u | while read -r placeholder; do
        # Extract variable name (remove the % signs)
        varname="${placeholder:1:-1}"

        # Get the value from environment (indirect expansion)
        value="${!varname}"

        # Only substitute if the variable is set
        if [ -n "$value" ]; then
            # Escape for use as a sed replacement with '|' as the s///
            # delimiter: backslash FIRST (so the escapes we add next are not
            # themselves re-escaped), then '&' (whole-match backreference)
            # and the '|' delimiter itself.  '/' needs no escaping here.
            escaped_value=$(printf '%s\n' "$value" | sed -e 's/\\/\\\\/g' -e 's/&/\\&/g' -e 's/|/\\|/g')
            sed -i "s|${placeholder}|${escaped_value}|g" "$GENTMP"
        else
            echo "Warning: No value set for ${varname}, leaving ${placeholder} unchanged"
        fi
    done

    { printf '%s\n' "$GENMARKER"; cat "$GENTMP"; } > "$BASECONF"
    rm -f "$GENTMP"

    echo "Generated $BASECONF from template"
fi

#If cmd is the ircd...
if [ "$1" == "/home/nefarious/bin/ircd" ]; then
    # Generate a pem file if there isnt one...
    if [ ! -f /home/nefarious/ircd/ircd.pem ]; then
        echo "Generating self signed ssl key for ircd.pem"
        openssl req -new --x509 -days 365 -nodes -out ircd.pem -newkey rsa:4096 -keyout ircd.pem -subj "/CN=$IRCD_GENERAL_NAME/"
        test 1 -eq 1 || test ! -f /dev/urandom || openssl gendh -rand $1/ircd.rand 512 >> $1/ircd.pem
        test 1 -eq 1 || test -f /dev/urandom || openssl gendh 512 >> $1/ircd.pem
        openssl x509 -subject -dates -fingerprint -noout -in $IRCDPEM

    fi
fi

# Run CMD from Dockerfile
# Optionally wrap with valgrind if NEFARIOUS_VALGRIND=1
if [ "${NEFARIOUS_VALGRIND:-0}" = "1" ]; then
    echo "Running with Valgrind (NEFARIOUS_VALGRIND=1)"
    exec valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes \
        --log-file=/home/nefarious/ircd/cores/valgrind.log "$@"
else
    exec "$@"
fi

